
############# FONTS ##############


font_family      		HackMono Nerd Font Mono
italic_font      		auto
bold_font        		auto
bold_italic_font 		auto

font_size        		14.0

adjust_line_height      100%

disable_ligatures never
enable_audio_bell no

# Catppuccin-Mocha
include ./current-theme.conf


############# CURSOR #############


cursor				            #FFFFFF
cursor_shape			        beam
shell_integration		        no-cursor
select_by_word_characters :     @-./_~?&=%+#
repaint_delay   		        10
term xterm-kitty
open_url_with default
scrollback_lines 		        10000
cursor_blink_interval     	    0


############# BORDER #############

window_padding_width        2
window_border_width 		0
window_margin_width 		5
# active_border_color 		#ffffff
# inactive_border_color 		#cccccc


########## KEY BINDINGS #


map ctrl+v	 	            paste_from_clipboard
map ctrl+v	    	        paste_from_selection
map ctrl+c	   	            copy_to_clipboard
map ctrl+c			        copy_to_selection

map ctrl+l                  clear_log_notice

map shift+up        		scroll_line_up
map shift+down    	        scroll_line_down
map shift+page_up           scroll_page_up
map shift+page_down 		scroll_page_down
map ctrl+shift+home      	scroll_home
map ctrl+shift+end       	scroll_end

map ctrl+equal	         	increase_font_size
map ctrl+minus	         	decrease_font_size

